# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_movie_list' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_movie_list
  pod 'Alamofire'
  pod 'AlamofireImage'

end
